name: stackfood_multivendor_driver
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.0.15
  connectivity_plus: ^5.0.2
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^16.3.0
  path_provider: ^2.0.10
  url_strategy: ^0.2.0
  pin_code_fields: ^8.0.1
  http: ^1.1.2
  flutter_switch: ^0.3.2
  shimmer_animation: ^2.1.0+1
  geolocator: ^10.1.0
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.6
  url_launcher: ^6.1.2
  vibration: ^1.7.6
  image_picker: ^1.0.7
  disable_battery_optimization: ^1.1.0+1
  phone_numbers_parser: ^8.1.3
  country_code_picker: ^3.0.0
  audioplayers: ^5.2.1
  flutter_widget_from_html_core: ^0.14.11
  intl: ^0.18.0
  path: ^1.8.2
  http_parser: ^4.0.2
  dotted_border: ^2.0.0+2
  photo_view: ^0.14.0
  flutter_inappwebview: ^6.0.0
  file_picker: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900